version: '3'

services:
  app1:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - server3
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp

  app2:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - server3
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp

  server3:
    build:
      context: ./
      dockerfile: Dockerfile.server3
    volumes:
      - ./photos:/go/src/app/photos


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  nginx:
    build: ./build/nginx
    ports:
      - "8080:8080"
    depends_on:
      - app1
      - app2
      - server3
